import { EventEmitter } from '@angular/core';
import { Router } from '@angular/router';
import { Observable } from 'rxjs/Observable';
import { HttpClient } from '@angular/common/http';
import { AuthorizationResult } from '../models/authorization-result.enum';
import { AuthConfiguration, OpenIDImplicitFlowConfiguration } from '../modules/auth.configuration';
import { StateValidationService } from './oidc-security-state-validation.service';
import { OidcSecurityCheckSession } from './oidc.security.check-session';
import { OidcSecurityCommon } from './oidc.security.common';
import { OidcSecuritySilentRenew } from './oidc.security.silent-renew';
import { OidcSecurityUserService } from './oidc.security.user-service';
import { OidcSecurityValidation } from './oidc.security.validation';
import { OidcDataService } from './oidc-data.service';
import { TokenHelperService } from './oidc-token-helper.service';
import { LoggerService } from './oidc.logger.service';
import { AuthWellKnownEndpoints } from '../models/auth.well-known-endpoints';
export declare class OidcSecurityService {
    private platformId;
    private oidcDataService;
    private stateValidationService;
    private authConfiguration;
    private router;
    private oidcSecurityCheckSession;
    private oidcSecuritySilentRenew;
    private oidcSecurityUserService;
    private oidcSecurityCommon;
    private oidcSecurityValidation;
    private tokenHelperService;
    private loggerService;
    private httpClient;
    onModuleSetup: EventEmitter<boolean>;
    onAuthorizationResult: EventEmitter<AuthorizationResult>;
    onCheckSessionChanged: EventEmitter<boolean>;
    checkSessionChanged: boolean;
    moduleSetup: boolean;
    private authWellKnownEndpoints;
    private _isAuthorized;
    private _isAuthorizedValue;
    private _isLoading;
    private _isLoadingValue;
    private lastUserData;
    private _userData;
    private authWellKnownEndpointsLoaded;
    private runTokenValidationRunning;
    private CheckForPopupClosedInterval;
    private _checkForPopupClosedTimer;
    private _popup;
    private _popupFor;
    private authenticationScheme;
    private loginMethod;
    constructor(platformId: Object, oidcDataService: OidcDataService, stateValidationService: StateValidationService, authConfiguration: AuthConfiguration, router: Router, oidcSecurityCheckSession: OidcSecurityCheckSession, oidcSecuritySilentRenew: OidcSecuritySilentRenew, oidcSecurityUserService: OidcSecurityUserService, oidcSecurityCommon: OidcSecurityCommon, oidcSecurityValidation: OidcSecurityValidation, tokenHelperService: TokenHelperService, loggerService: LoggerService, httpClient: HttpClient);
    setupModule(openIDImplicitFlowConfiguration: OpenIDImplicitFlowConfiguration, authWellKnownEndpoints: AuthWellKnownEndpoints): void;
    getUserData(): Observable<any>;
    getIsAuthorized(): Observable<boolean>;
    getToken(): string;
    getIdToken(): string;
    getPayloadFromIdToken(encode?: boolean): any;
    setState(state: string): void;
    getState(): string;
    setCustomRequestParameters(params: {
        [key: string]: string | number | boolean;
    }): void;
    popup_cleanup(): void;
    _checkForPopupClosed(): void;
    _checkForLogoutPopupClosed(): void;
    popup_login(url: string, title: string, w: number, h: number): void;
    authorize(authenticationScheme?: string, loginMethod?: string): void;
    authorizedCallback(hash?: string): void;
    getUserinfo(isRenewProcess?: boolean, result?: any, id_token?: any, decoded_id_token?: any): Observable<boolean>;
    logoff(): Promise<void>;
    refreshSession(): void;
    handleError(error: any): void;
    private getValidatedStateResult(result, jwtKeys);
    private setUserData(userData);
    private setIsAuthorized(isAuthorized);
    private setAuthorizationData(access_token, id_token);
    getIsLoading(): Observable<boolean>;
    private setIsLoading(isAuthorized);
    private createAuthorizeUrl(nonce, state, authorization_endpoint, prompt?);
    private createEndSessionUrl(end_session_endpoint, id_token_hint);
    private resetAuthorizationData(isRenewProcess);
    private onUserDataChanged();
    private getSigningKeys();
    private handleErrorGetSigningKeys(error);
    private runTokenValidation();
}
